apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: f1-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-app
  template:
    metadata:
      labels:
        app: mlflow-app
    spec:
      containers:
        - name: mlflow-app
          image: docker.io/evk02/mlflow:2.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10 