apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: f1-platform
spec:
  type: NodePort
  selector:
    app: mlflow-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http