apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  selector:
    app: mlflow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http